title: Álex Fernández # your name (or website title) here
logo: "/images/logo.png" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Data Analyst & BI Developer
  <br><br>
  Economist oriented in the development and deployment of BI/Data Science processes and the implementation of data-driven operations. Constantly involved in a self-development and learning process through formation and consistency.
  <br><br>
  <a href="https://www.linkedin.com/in/alejandro-fernandez-rodriguez/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
